apiVersion: v2
name: retool
description: A Helm chart for Kubernetes
type: application
version: 5.0.4
maintainers:
  - name: Retool Engineering
    email: engineering+helm@retool.com
dependencies:
  - name: postgresql-12.1.5
    version: 12.1.5
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
